//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadInvoiceWpf.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReadInvoiceWpf.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        internal static string CustomerAddrLbl {
            get {
                return ResourceManager.GetString("CustomerAddrLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri.
        /// </summary>
        internal static string CustomerBlck {
            get {
                return ResourceManager.GetString("CustomerBlck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şehir.
        /// </summary>
        internal static string CustomerCityLbl {
            get {
                return ResourceManager.GetString("CustomerCityLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adı.
        /// </summary>
        internal static string CustomerLbl {
            get {
                return ResourceManager.GetString("CustomerLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        internal static string CustomerPhoneLbl {
            get {
                return ResourceManager.GetString("CustomerPhoneLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vergi No.
        /// </summary>
        internal static string CustomerTaxIdLbl {
            get {
                return ResourceManager.GetString("CustomerTaxIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vergi Dairesi.
        /// </summary>
        internal static string CustomerTaxOfficeLbl {
            get {
                return ResourceManager.GetString("CustomerTaxOfficeLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlçe.
        /// </summary>
        internal static string CustomerTownLbl {
            get {
                return ResourceManager.GetString("CustomerTownLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string DetailTab {
            get {
                return ResourceManager.GetString("DetailTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İndirim.
        /// </summary>
        internal static string DiscExclVatLbl {
            get {
                return ResourceManager.GetString("DiscExclVatLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Yolu.
        /// </summary>
        internal static string FilePath {
            get {
                return ResourceManager.GetString("FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Yolu.
        /// </summary>
        internal static string FilePathLbl {
            get {
                return ResourceManager.GetString("FilePathLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brüt Toplam.
        /// </summary>
        internal static string GrandTotalExclVatLbl {
            get {
                return ResourceManager.GetString("GrandTotalExclVatLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura.
        /// </summary>
        internal static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura Görseli.
        /// </summary>
        internal static string InvoiceViewTab {
            get {
                return ResourceManager.GetString("InvoiceViewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura Gösterimi.
        /// </summary>
        internal static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notlar.
        /// </summary>
        internal static string NotesLbl {
            get {
                return ResourceManager.GetString("NotesLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Aç.
        /// </summary>
        internal static string OpenFileBtn {
            get {
                return ResourceManager.GetString("OpenFileBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alıcı Email.
        /// </summary>
        internal static string RecevieEmailLbl {
            get {
                return ResourceManager.GetString("RecevieEmailLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alıcı Kimliği.
        /// </summary>
        internal static string RecevierIdentityLbl {
            get {
                return ResourceManager.GetString("RecevierIdentityLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alıcı Ünvanı.
        /// </summary>
        internal static string RecevierTitleLbl {
            get {
                return ResourceManager.GetString("RecevierTitleLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görüntü Yenile.
        /// </summary>
        internal static string ReView {
            get {
                return ResourceManager.GetString("ReView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil Seçimi.
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönderici Eposta.
        /// </summary>
        internal static string SenderEmailLbl {
            get {
                return ResourceManager.GetString("SenderEmailLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönderici Kimliği.
        /// </summary>
        internal static string SenderIdentityLbl {
            get {
                return ResourceManager.GetString("SenderIdentityLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönderici Unvanı.
        /// </summary>
        internal static string SenderTitleLbl {
            get {
                return ResourceManager.GetString("SenderTitleLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tedarikçi Adresi.
        /// </summary>
        internal static string SupplierAddrLbl {
            get {
                return ResourceManager.GetString("SupplierAddrLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tedarikçi.
        /// </summary>
        internal static string SupplierBlck {
            get {
                return ResourceManager.GetString("SupplierBlck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şehir.
        /// </summary>
        internal static string SupplierCityLbl {
            get {
                return ResourceManager.GetString("SupplierCityLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tedarikçi Adı.
        /// </summary>
        internal static string SupplierLbl {
            get {
                return ResourceManager.GetString("SupplierLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        internal static string SupplierPhoneLbl {
            get {
                return ResourceManager.GetString("SupplierPhoneLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vergi Kimlik No.
        /// </summary>
        internal static string SupplierTaxIdLbl {
            get {
                return ResourceManager.GetString("SupplierTaxIdLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vergi Dairesi.
        /// </summary>
        internal static string SupplierTaxOfficeLbl {
            get {
                return ResourceManager.GetString("SupplierTaxOfficeLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlçe.
        /// </summary>
        internal static string SupplierTownLbl {
            get {
                return ResourceManager.GetString("SupplierTownLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam.
        /// </summary>
        internal static string TotalLbl {
            get {
                return ResourceManager.GetString("TotalLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KDV.
        /// </summary>
        internal static string VatTotal {
            get {
                return ResourceManager.GetString("VatTotal", resourceCulture);
            }
        }
    }
}
